project:
  type: website
  output-dir: docs

website:
  title: "El ABC de las funciones"
  navbar:
    left:
      - href: index.qmd
        text: ABC
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 2
    toc-expand: 2
    number-sections: true
    number-depth: 2
    code-copy: true
    code-fold: show
    code-summary: "Mostrar código"
    code-tools: true
    code-overflow: wrap

editor: visual

